function gs_soc_model_setup(hFPGA)
%--------------------------------------------------------------------------
% Host Interface Script Setup
% 
% This function was created for the IP Core generated from design 'soc_model'.
% 
% Run this function on an "fpga" object to configure it with the same interfaces as the generated IP core.
%--------------------------------------------------------------------------

%% AXI4-Lite
addAXI4SlaveInterface(hFPGA, ...
	"InterfaceID", "AXI4-Lite", ...
	"BaseAddress", 0xA0000000, ...
	"AddressRange", 0x10000);

DUTPort_w1 = hdlcoder.DUTPort("w1", ...
	"Direction", "IN", ...
	"DataType", numerictype(1,18,16), ...
	"IsComplex", true, ...
	"Dimension", [1 4], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x100");

DUTPort_w2 = hdlcoder.DUTPort("w2", ...
	"Direction", "IN", ...
	"DataType", numerictype(1,18,16), ...
	"IsComplex", true, ...
	"Dimension", [1 4], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x140");

DUTPort_w3 = hdlcoder.DUTPort("w3", ...
	"Direction", "IN", ...
	"DataType", numerictype(1,18,16), ...
	"IsComplex", true, ...
	"Dimension", [1 4], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x180");

DUTPort_w4 = hdlcoder.DUTPort("w4", ...
	"Direction", "IN", ...
	"DataType", numerictype(1,18,16), ...
	"IsComplex", true, ...
	"Dimension", [1 4], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x1C0");

DUTPort_chEnable = hdlcoder.DUTPort("chEnable", ...
	"Direction", "IN", ...
	"DataType", numerictype(0,1,0), ...
	"IsComplex", false, ...
	"Dimension", [1 4], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x1F0");

DUTPort_modSel = hdlcoder.DUTPort("modSel", ...
	"Direction", "IN", ...
	"DataType", numerictype(0,1,0), ...
	"IsComplex", false, ...
	"Dimension", [1 4], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x210");

DUTPort_OFDMmodType = hdlcoder.DUTPort("OFDMmodType", ...
	"Direction", "IN", ...
	"DataType", numerictype(0,2,0), ...
	"IsComplex", false, ...
	"Dimension", [1 4], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x230");

DUTPort_SCmodType = hdlcoder.DUTPort("SCmodType", ...
	"Direction", "IN", ...
	"DataType", numerictype(0,2,0), ...
	"IsComplex", false, ...
	"Dimension", [1 4], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x250");

DUTPort_tuningWord = hdlcoder.DUTPort("tuningWord", ...
	"Direction", "IN", ...
	"DataType", "int16", ...
	"IsComplex", false, ...
	"Dimension", [1 4], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x270");

DUTPort_modEnable = hdlcoder.DUTPort("modEnable", ...
	"Direction", "IN", ...
	"DataType", numerictype(0,1,0), ...
	"IsComplex", false, ...
	"Dimension", [1 4], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x290");

DUTPort_amplitude = hdlcoder.DUTPort("amplitude", ...
	"Direction", "IN", ...
	"DataType", numerictype(1,18,16), ...
	"IsComplex", true, ...
	"Dimension", [1 4], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x2C0");

mapPort(hFPGA, [DUTPort_w1, DUTPort_w2, DUTPort_w3, DUTPort_w4, DUTPort_chEnable, DUTPort_modSel, DUTPort_OFDMmodType, DUTPort_SCmodType, DUTPort_tuningWord, DUTPort_modEnable, DUTPort_amplitude]);

end
